name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: ozonep/openwrt
        username: ozonep
        password: ${{ secrets.DOCKER_TOKEN }}